
const LSKEYS = {
    __LSKEY_PROMPT_SOURCE_STR__: "__LSKEY_PROMPT_SOURCE_STR__",
    __LSKEY_PROMPT_SELECTED__: "__LSKEY_PROMPT_SELECTED__",
    __LSKEY_PROMPT_HISTORY__: "__LSKEY_PROMPT_HISTORY__",
};

export default LSKEYS;
